# Generated by Django 5.1.6 on 2025-05-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprogress_lesson_steps_completed_learningoutcome_and_more'),
        ('quiz', '0002_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('ky', 'Кыргызский')], db_index=True, default='ru', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['author', 'is_published'], name='core_course_author__438780_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['language', 'is_published'], name='core_course_languag_de7a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='core_lesson_module__bc71c5_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='core_module_course__d6848a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'course'], name='core_userpr_user_id_544386_idx'),
        ),
    ]
