# Generated by Django 5.1.6 on 2025-05-01 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_course_is_published_alter_course_language_and_more'),
        ('quiz', '0002_alter_choice_options_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Единственный выбор'), ('multiple', 'Множественный выбор'), ('true_false', 'Верно/Неверно'), ('short_answer', 'Короткий ответ')], db_index=True, default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quiz_questi_quiz_id_f13328_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'is_published'], name='quiz_quiz_course__f0bd88_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['module'], name='quiz_quiz_module__7c69eb_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user'], name='quiz_quizat_quiz_id_fd8459_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'is_completed'], name='quiz_quizat_user_id_8a8dc9_idx'),
        ),
    ]
