# Generated by Django 5.1.6 on 2025-04-20 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='start_date',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код контакта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(verbose_name='Стаж (в годах)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=100, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='medical.specialization', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='medical.disease', verbose_name='Болезнь'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='medical.doctor', verbose_name='Лечащий врач'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='medical.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Вылечен'), (1, 'В процессе лечения')], default=1, verbose_name='Статус болезни'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
