# Generated by Django 5.1.6 on 2025-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_remove_medicalhistory_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
